# Generated by: Neurodocker version 0.7.0+0.gdc97516.dirty
# Latest release: Neurodocker version 0.7.0
# Timestamp: 2021/05/13 21:33:39 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/ReproNim/neurodocker

FROM neurodebian:bullseye

USER root

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends neurodebian-freeze \
    && nd_freeze  20210510T000000Z \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           vim \
           wget \
           strace \
           time \
           ncdu \
           gnupg \
           curl \
           procps \
           git \
           pigz \
           less \
           tree \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN cd /tmp/ && git clone -b env/ohbm http://github.com/sparkletown/sparkle && cd sparkle && npm install -g && cd /tmp && rm -rf sparkle

RUN test "$(getent passwd sparkle)" || useradd --no-user-group --create-home --shell /bin/bash sparkle
USER sparkle

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "neurodebian:bullseye" \
    \n    ], \
    \n    [ \
    \n      "ndfreeze", \
    \n      { \
    \n        "date": "20210510T000000Z" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "vim", \
    \n        "wget", \
    \n        "strace", \
    \n        "time", \
    \n        "ncdu", \
    \n        "gnupg", \
    \n        "curl", \
    \n        "procps", \
    \n        "git", \
    \n        "pigz", \
    \n        "less", \
    \n        "tree" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "curl -sL https://deb.nodesource.com/setup_14.x | bash - " \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "nodejs" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "cd /tmp/ && git clone -b env/ohbm http://github.com/sparkletown/sparkle && cd sparkle && npm install -g && cd /tmp && rm -rf sparkle" \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "sparkle" \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
